### ISSUE TITLE
Can't seem to get markAsSeen() to work.

### ISSUE THREAD

**Issue by zapling** [fbchat-dev/fbchat#171]
I can't get **markAsSeen()** to work. There is not enough documentation for me to know if I'm doing something wrong.

This is my code.
```
class MessengerBot(Client):

    def onMessage(self, mid, author_id, message, thread_id, thread_type, ts, metadata, msg, **kwargs):
        self.markAsSeen()
```
I get this printed to the console.
```
DEBUG:client:Unknown message received: {u'queue': 100018675074457L, u'ofd_ts': 1
498735226994L, u'iseq': 85, u'type': u'delta', u'delta': {u'folders': [u'FOLDER_
INBOX'], u'irisSeqId': u'85', u'class': u'MarkFolderSeen', u'timestamp': u'14987
35236919'}}
```
Is it something I need to call before **markAsSeen()** or have facebook changed something on their end?

**Comment by madsmtm** [comment]
I think `markAsSeen()` is, sadly, currently broken. That's also why it's one of the things with missing documentation ;)

**Comment by zapling** [comment]
Okay, thanks for clearing it up for me :thumbsup:
