### ISSUE TITLE
Add @kapi2289 as project collaborator

### ISSUE THREAD

**Issue by madsmtm** [fbchat-dev/fbchat#390]
Hey @carpedm20, I've been working a lot with @kapi2289 lately, and I'd like to suggest adding him as a collaborator to the project. (🎉 🎉)

He's the second-biggest contributor to the project, and I've been IM-ing him for while, and can vouch for his determination to the project. Making him a collaborator would put him on the same "level" as me, and would make it easier for me to continue a mutually beneficial relationship with him.
I'm making this request in a public channel, so that anyone can object to it, or suggest other candidates, if they feel like it.

As a more general note: I'm sorry to bother you about these requests, I know you're busy with a lot of other things. Alternatively, you could transfer the repository to me? Or I could create a Github organization, and we could move the repo there? That would allow multiple people to be administrators, and would allow collaborators to manage a few other things in the repository (like deploy keys, integrations and such). But if you don't feel like it, we can of course delay this to some other time. 😊😉

**Comment by TheSkilerPL** [comment]
i dont want him he is a bad dev look at his site how he done it ( minecraftmapy.pl )

**Comment by madsmtm** [comment]
Fixed by https://github.com/carpedm20/fbchat/issues/613#issuecomment-701363292 🎉
