### ISSUE TITLE
V2: Get UserData form Group

### ISSUE THREAD

**Issue by TheToto** [fbchat-dev/fbchat#599]
There is no call to get users details from a group id.
Before this commit https://github.com/carpedm20/fbchat/commit/5e09cb9cab5d93db81dd42e7566d068f01d35b61, there was `fetch_all_users_from_threads`.

I can get `User` objects with `Thread.participants`, but i can't find a way to get a `UserData`

Is there a new method to fetch users détails from group id ?

**Comment by wetmore** [comment]
You can get UserData with thread.fetch_thread_info([user_id1, user_id2...])
